// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using permissionAPI;

#nullable disable

namespace workshop2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240916103539_mssql_migration_909")]
    partial class mssql_migration_909
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("permissionAPI.src.Entities.RoleDbo", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("role");
                });

            modelBuilder.Entity("permissionAPI.src.Entities.UserDbo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Lastname")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_lastname");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("address")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_address");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_phone");

                    b.Property<string>("status")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_status");

                    b.HasKey("UserID");

                    b.ToTable("User", "custom_schema");
                });

            modelBuilder.Entity("permissionAPI.src.Entities.number1Dbo", b =>
                {
                    b.Property<int>("CimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CimID"));

                    b.Property<string>("cim")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cim");

                    b.HasKey("CimID");

                    b.ToTable("number1", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
